#!/bin/bash
rm -f ../../../../fonts/tfm/contrib/aecc/*.tfm ../../../../fonts/vf/contrib/aecc/*.vf
rm -f ../../../../tex/latex/contrib/aecc/t1aeccr.fd
mv *.tfm ../../../../fonts/tfm/contrib/aecc/
mv *.vf ../../../../fonts/vf/contrib/aecc/
mv t1aeccr.fd ../../../../tex/latex/contrib/aecc/
