This is a Type1 version of Calligra font by Peter Vanroose.  Converted from
MetaFont source using `mf2pt1' tool with no manual intervention (though the
output were verified against high resolution bitmaps generated by MataFont).

`mf2pt1' was called with the following options:
mf2pt1 --designsize=15 --encoding=t1 \
       --name=CALLIG15 --family=CALLIG15 --fullname=CALLIG15 \
       --comment="Copyright 1992 Peter Vanroose, 1999 S. Dachian\nYou may \
freely use, modify and/or distribute this file, as long as this copyright \
notice is retained" \
       callig15

Original copyright notice:
  Copyright 1992 Peter Vanroose, 1999 S. Dachian
  You may freely use, modify and/or distribute this file (original source:
  CTAN:fonts/calligra), as long as this copyright notice is retained.
